# Generated by Django 5.0.6 on 2024-05-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Число завершенных пректов')),
                ('review', models.IntegerField(verbose_name='Число отзывов')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AddField(
            model_name='services',
            name='desc',
            field=models.TextField(default=1, verbose_name='Описание для связи'),
            preserve_default=False,
        ),
    ]
