# Generated by Django 5.0.6 on 2024-05-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_projects_services_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.BigIntegerField(verbose_name='С')),
                ('po', models.BigIntegerField(verbose_name='по')),
                ('name', models.CharField(max_length=255, verbose_name='Место обучение')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Образвание',
                'verbose_name_plural': 'Образвание',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Скилл')),
            ],
            options={
                'verbose_name': 'Скиллы',
                'verbose_name_plural': 'Скиллы',
            },
        ),
    ]
