# Generated by Django 5.0.6 on 2024-05-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_education_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/', verbose_name='ОПИСАНИЕ')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('silka', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Последенее партфолио',
                'verbose_name_plural': 'Последенее партфолио',
            },
        ),
    ]
