# Generated by Django 5.0.6 on 2024-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_parfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/', verbose_name='Фото')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('dol', models.CharField(max_length=255, verbose_name='Должность')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отзывы клиентов',
                'verbose_name_plural': 'Отзывы клиентов',
            },
        ),
    ]
