# Generated by Django 5.0.6 on 2024-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='photo/', verbose_name='Фотография')),
                ('job', models.CharField(max_length=255, verbose_name='Профессия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Основная настройка',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
